### PR TITLE
Sexy readme

### PR DESCRIPTION
**Pull request by Hampusm**
I made a sexy readme.

### CODE REVIEW

**Comment by Hampusm** [comment]
@KartSriv I know that i have pull access but i still think it may be a good idea to ask you first on this one as this requires a mobile version of the readme too

**Comment by Hampusm** [comment]
You can see it at [my fork](https://github.com/Hampusm/Story)

**Comment by KartSriv** [comment]
@Hampusm That's actually a really nice README but having a separate README for mobile user is not seeming right at least to me so I'll create a branch called SexyREADME then I'll replace the current README with yours from the fork then I'll fix some formatting so it'll work for both mobile and desktop then we can merge the branch.

**Comment by KartSriv** [comment]
Check out https://github.com/KartSriv/Story/blob/SexyREADME/README.md

**Comment by Hampusm** [comment]
Whats even the point of it if its on another branch

**Comment by KartSriv** [comment]
@Hampusm Just want to confirm.

**Pull request closed without merging**
